name: portfolio1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/features/core/constants/fonts.dart
    - lib/features/core/constants/colors.dart
    - lib/assets/images/user_profile.jpg

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic
  #   - family: NotoSans
  #     fonts:
  #       - asset: assets/fonts/NotoSans-Regular.ttf
  #       - asset: assets/fonts/NotoSans-Bold.ttf
  #         weight: 700
  #   - family: NotoSerif
  #     fonts:
  #       - asset: assets/fonts/NotoSerif-Regular.ttf
  #       - asset: assets/fonts/NotoSerif-Bold.ttf
  #         weight: 700
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
  #   - family: Lato
  #     fonts:
  #       - asset: assets/fonts/Lato-Regular.ttf
  #       - asset: assets/fonts/Lato-Bold.ttf
  #         weight: 700
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #       - asset: assets/fonts/OpenSans-Bold.ttf
  #         weight: 700
  #   - family: SourceSansPro
  #     fonts:
  #       - asset: assets/fonts/SourceSansPro-Regular.ttf
  #       - asset: assets/fonts/SourceSansPro-Bold.ttf
  #         weight: 700
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Bold.ttf
  #         weight: 700
